name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: Zenisis/n-est-app # Use your actual GitHub username and repository name

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Create directory on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@54.174.84.153 'mkdir -p /home/ubuntu/nestjs'

    - name: Copy files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -r . ubuntu@54.174.84.153:/home/ubuntu/nestjs

    - name: SSH and deploy
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@54.174.84.153 << 'EOF'
          cd /home/ubuntu/nestjs
          npm install
          npm run build
          npm run start
        EOF
